### ISSUE TITLE
AOT support

### ISSUE THREAD

**Issue by Ignas-StormGeo** [nmangue/NGrib#12]
Hello.

As GRIB reading needs to be high-performance, ahead-of-time (AOT) compiling helps with that. However it has two clear requirements: .net 8.0 (or 7.0 but it doesn't have LTS) is needed plus the code itself must not have any reflection.
Would it be possible to do that for NGrib?
More to read: https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/?tabs=net7%2Cwindows

**Comment by nmangue** [comment]
Hello,

This could be a nice addition. I have done a quick build test and there seems to be no blocking issue. The reflection code NGrib uses, is compatible with AOT (only some specific actions like emitting code is not compatible with AOT).
I will have to do more tests and update the Nuget packaging to add a net8 target for it to be releasable.

**Comment by nmangue** [comment]
Fixed by PR #20
