### ISSUE TITLE
Is there any usage examples?

### ISSUE THREAD

**Issue by arisliang** [nmangue/NGrib#7]
Couldn't find any usage examples. Would be great if there's some.

**Comment by nmangue** [comment]
Hello,

Unfortunately, for now there are no documentation. You can use the unit tests as reference to read GRIB files data. The base usage :

```
using var stream = File.OpenRead("sample.grib");
var reader = new Grib2Reader(stream);

var datasets = reader.ReadAllDataSets();

var temperatureDs = datasets.Single(d => d.Parameter.Equals(Parameter.Temperature));

var data = reader.ReadDataSetValues(temperatureDs);
```

To find information about the content (i.e. the GRIB sections, the templates, the field values...) please refer to the official specifications :
* GRIB1 : https://codes.ecmwf.int/grib/format/grib1/overview/
* GRIB2 : https://codes.ecmwf.int/grib/format/grib2/overview/
